export const Paths = {
  home: 'home',
  login: 'login',
  register: 'register',
  dashboard: 'dashboard',
  profile: 'profile',
  settings: 'settings',
  studentStats: 'student-stats',
  teacherStats: 'teacher-stats',
  CoursesList : 'courses-list',
  createTest: 'create-test',
  courseDetails: 'courses/:courseId',
  courseChapter: 'courses/:courseId/chapters/:chapterId',
  takeTest: 'test/:chapterId/:level',
  testResults: 'test/:chapterId/results',
};