import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    padding: '32px',
    backgroundColor: '#f9fafb',
    minHeight: '100vh',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '32px',
  },
  title: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: '8px',
  },
  subtitle: {
    fontSize: '16px',
    color: '#6b7280',
  },
  select: {
    padding: '10px 16px',
    border: '2px solid #e5e7eb',
    borderRadius: '8px',
    fontSize: '14px',
    outline: 'none',
    backgroundColor: 'white',
    cursor: 'pointer',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '24px',
    marginBottom: '32px',
  },
  statCard: {
    backgroundColor: 'white',
    padding: '24px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '16px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  statIcon: {
    width: '48px',
    height: '48px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statContent: {
    flex: 1,
  },
  statLabel: {
    fontSize: '14px',
    color: '#6b7280',
    marginBottom: '8px',
  },
  statValueRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '4px',
    marginBottom: '4px',
  },
  statValue: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#1f2937',
  },
  statTotal: {
    fontSize: '20px',
    color: '#9ca3af',
  },
  statChange: {
    fontSize: '13px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  mainLayout: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr',
    gap: '24px',
  },
  leftColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  rightColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
  },
  section: {
    backgroundColor: 'white',
    padding: '24px',
    borderRadius: '12px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  sectionTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  chartContainer: {
    padding: '20px 0',
  },
  chartBars: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'flex-end',
    height: '250px',
    gap: '8px',
  },
  barWrapper: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  bar: {
    width: '100%',
    background: 'linear-gradient(180deg, #14b8a6 0%, #06b6d4 100%)',
    borderRadius: '8px 8px 0 0',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingTop: '8px',
    minHeight: '40px',
  },
  barValue: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: 'white',
  },
  barLabel: {
    fontSize: '12px',
    color: '#6b7280',
    marginTop: '8px',
  },
  barTests: {
    fontSize: '10px',
    color: '#9ca3af',
    marginTop: '2px',
  },
  subjectsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  subjectCard: {
    padding: '20px',
    backgroundColor: '#f9fafb',
    borderRadius: '12px',
    border: '1px solid #e5e7eb',
  },
  subjectHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '16px',
  },
  subjectInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  subjectDot: {
    width: '12px',
    height: '12px',
    borderRadius: '50%',
  },
  subjectName: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#1f2937',
  },
  subjectMeta: {
    fontSize: '12px',
    color: '#9ca3af',
  },
  subjectBadge: {
    display: 'flex',
    gap: '8px',
  },
  strengthBadge: {
    fontSize: '12px',
    fontWeight: '600',
    padding: '4px 12px',
    borderRadius: '12px',
  },
  subjectScores: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '12px',
    marginBottom: '12px',
  },
  scoreItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  scoreLabel: {
    fontSize: '11px',
    color: '#9ca3af',
  },
  scoreValue: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#1f2937',
  },
  lastGrade: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  subjectBar: {
    height: '8px',
    backgroundColor: '#e5e7eb',
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '8px',
  },
  subjectBarFill: {
    height: '100%',
    transition: 'width 0.3s ease',
  },
  comparison: {
    fontSize: '12px',
    fontWeight: '500',
  },
  testsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  testItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px',
    backgroundColor: '#f9fafb',
    borderRadius: '8px',
    border: '1px solid #e5e7eb',
  },
  testInfo: {
    flex: 1,
  },
  testSubject: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#14b8a6',
    marginBottom: '4px',
  },
  testName: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: '4px',
  },
  testDate: {
    fontSize: '12px',
    color: '#9ca3af',
  },
  testScores: {
    display: 'flex',
    gap: '24px',
    alignItems: 'center',
  },
  testGrade: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  gradeValue: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: '#14b8a6',
  },
  gradeLabel: {
    fontSize: '11px',
    color: '#9ca3af',
  },
  testComparison: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  comparisonValue: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#10b981',
  },
  comparisonLabel: {
    fontSize: '11px',
    color: '#9ca3af',
  },
  habitsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  habitItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '16px',
    backgroundColor: '#f9fafb',
    borderRadius: '8px',
  },
  habitIcon: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    backgroundColor: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  habitContent: {
    flex: 1,
  },
  habitLabel: {
    fontSize: '12px',
    color: '#9ca3af',
    marginBottom: '4px',
  },
  habitValue: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#1f2937',
  },
  achievementsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  achievementCard: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '16px',
    backgroundColor: '#f0fdfa',
    border: '2px solid #14b8a6',
    borderRadius: '8px',
    position: 'relative',
  },
  achievementCardLocked: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '16px',
    backgroundColor: '#f9fafb',
    border: '2px solid #e5e7eb',
    borderRadius: '8px',
    opacity: 0.6,
  },
  achievementIcon: {
    fontSize: '36px',
  },
  achievementContent: {
    flex: 1,
  },
  achievementTitle: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: '4px',
  },
  achievementDescription: {
    fontSize: '12px',
    color: '#6b7280',
    marginBottom: '4px',
  },
  achievementDate: {
    fontSize: '11px',
    color: '#14b8a6',
  },
  achievementRarity: {
    fontSize: '10px',
    fontWeight: '600',
    color: '#9ca3af',
    backgroundColor: 'white',
    padding: '4px 8px',
    borderRadius: '8px',
  },
  quickStats: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  quickStatItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px',
    backgroundColor: '#f9fafb',
    borderRadius: '8px',
  },
  quickStatText: {
    fontSize: '14px',
    color: '#1f2937',
    fontWeight: '500',
  },
};
